# ===============================
# = DATA SOURCE CONFIGURATION =
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

# ===============================
# = JPA / HIBERNATE CONFIG =
# ===============================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# = SERVER CONFIG =
# ===============================
server.port=8080

# Optional: log SQL formatting (for readability)
spring.jpa.properties.hibernate.format_sql=true


# JWT
jwt.secret=9f8e1c2a7b0d4e6f3a1d8c7b9f2e5a0d6c3b8e4f9a1c7d5e2f0b3c6a8d4e9f2
jwt.expiration-ms=3600000
